//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_Issue_Project", "Project", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.Project), "Issue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.Issue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_Issue_User", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.User), "Issue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.Issue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_Issue_User1", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Domain.User), "Issue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.Issue))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_ProjectTeam_Project", "Project", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.Project), "ProjectTeam", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.ProjectTeam))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_ProjectTeam_Role", "Role", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.Role), "ProjectTeam", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.ProjectTeam))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_ProjectTeam_User", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.User), "ProjectTeam", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.ProjectTeam))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("bugtrackerModel", "FK_Issue_IssueType", "IssueType", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Domain.IssueType), "Issue", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Domain.Issue))]

// Original file name:
// Generation date: 21.12.2008 17:23:18
namespace BugTracker.Domain
{
    
    /// <summary>
    /// There are no comments for DBContext in the schema.
    /// </summary>
    public partial class DBContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new DBContext object using the connection string found in the 'DBContext' section of the application configuration file.
        /// </summary>
        public DBContext() : 
                base("name=DBContext", "DBContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBContext object.
        /// </summary>
        public DBContext(string connectionString) : 
                base(connectionString, "DBContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new DBContext object.
        /// </summary>
        public DBContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "DBContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Issue in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Issue> Issue
        {
            get
            {
                if ((this._Issue == null))
                {
                    this._Issue = base.CreateQuery<Issue>("[Issue]");
                }
                return this._Issue;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Issue> _Issue;
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Project> Project
        {
            get
            {
                if ((this._Project == null))
                {
                    this._Project = base.CreateQuery<Project>("[Project]");
                }
                return this._Project;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Project> _Project;
        /// <summary>
        /// There are no comments for ProjectTeam in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProjectTeam> ProjectTeam
        {
            get
            {
                if ((this._ProjectTeam == null))
                {
                    this._ProjectTeam = base.CreateQuery<ProjectTeam>("[ProjectTeam]");
                }
                return this._ProjectTeam;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProjectTeam> _ProjectTeam;
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Role> Role
        {
            get
            {
                if ((this._Role == null))
                {
                    this._Role = base.CreateQuery<Role>("[Role]");
                }
                return this._Role;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Role> _Role;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("[User]");
                }
                return this._User;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _User;
        /// <summary>
        /// There are no comments for IssueType in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<IssueType> IssueType
        {
            get
            {
                if ((this._IssueType == null))
                {
                    this._IssueType = base.CreateQuery<IssueType>("[IssueType]");
                }
                return this._IssueType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<IssueType> _IssueType;
        /// <summary>
        /// There are no comments for Issue in the schema.
        /// </summary>
        public void AddToIssue(Issue issue)
        {
            base.AddObject("Issue", issue);
        }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        public void AddToProject(Project project)
        {
            base.AddObject("Project", project);
        }
        /// <summary>
        /// There are no comments for ProjectTeam in the schema.
        /// </summary>
        public void AddToProjectTeam(ProjectTeam projectTeam)
        {
            base.AddObject("ProjectTeam", projectTeam);
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        public void AddToRole(Role role)
        {
            base.AddObject("Role", role);
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
        /// <summary>
        /// There are no comments for IssueType in the schema.
        /// </summary>
        public void AddToIssueType(IssueType issueType)
        {
            base.AddObject("IssueType", issueType);
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.Issue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="Issue")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Issue : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Issue object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="short">Initial value of Short.</param>
        public static Issue CreateIssue(int id, string @short)
        {
            Issue issue = new Issue();
            issue.Id = id;
            issue.Short = @short;
            return issue;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Short in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Short
        {
            get
            {
                return this._Short;
            }
            set
            {
                this.OnShortChanging(value);
                this.ReportPropertyChanging("Short");
                this._Short = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Short");
                this.OnShortChanged();
            }
        }
        private string _Short;
        partial void OnShortChanging(string value);
        partial void OnShortChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property Result in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this._Result;
            }
            set
            {
                this.OnResultChanging(value);
                this.ReportPropertyChanging("Result");
                this._Result = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Result");
                this.OnResultChanged();
            }
        }
        private string _Result;
        partial void OnResultChanging(string value);
        partial void OnResultChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_Project", "Project")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Project Project
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_Issue_Project", "Project").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_Issue_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Project> ProjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_Issue_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Project>("bugtrackerModel.FK_Issue_Project", "Project", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_User", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User Owner
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> OwnerReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("bugtrackerModel.FK_Issue_User", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for AssignedTo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_User1", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User AssignedTo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User1", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for AssignedTo in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> AssignedToReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_Issue_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("bugtrackerModel.FK_Issue_User1", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_IssueType", "IssueType")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public IssueType Type
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<IssueType>("bugtrackerModel.FK_Issue_IssueType", "IssueType").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<IssueType>("bugtrackerModel.FK_Issue_IssueType", "IssueType").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<IssueType> TypeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<IssueType>("bugtrackerModel.FK_Issue_IssueType", "IssueType");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<IssueType>("bugtrackerModel.FK_Issue_IssueType", "IssueType", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="Project")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Project : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Project CreateProject(int id, string name)
        {
            Project project = new Project();
            project.Id = id;
            project.Name = name;
            return project;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Issues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_Project", "Issue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Issue> Issues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Issue>("bugtrackerModel.FK_Issue_Project", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Issue>("bugtrackerModel.FK_Issue_Project", "Issue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_Project", "ProjectTeam")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProjectTeam> Team
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_Project", "ProjectTeam");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_Project", "ProjectTeam", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.ProjectTeam in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="ProjectTeam")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProjectTeam : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProjectTeam object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static ProjectTeam CreateProjectTeam(int id)
        {
            ProjectTeam projectTeam = new ProjectTeam();
            projectTeam.Id = id;
            return projectTeam;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_Project", "Project")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Project Project
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_ProjectTeam_Project", "Project").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_ProjectTeam_Project", "Project").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Project> ProjectReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Project>("bugtrackerModel.FK_ProjectTeam_Project", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Project>("bugtrackerModel.FK_ProjectTeam_Project", "Project", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_Role", "Role")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Role Role
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("bugtrackerModel.FK_ProjectTeam_Role", "Role").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("bugtrackerModel.FK_ProjectTeam_Role", "Role").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Role in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Role> RoleReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Role>("bugtrackerModel.FK_ProjectTeam_Role", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Role>("bugtrackerModel.FK_ProjectTeam_Role", "Role", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_User", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_ProjectTeam_User", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_ProjectTeam_User", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("bugtrackerModel.FK_ProjectTeam_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("bugtrackerModel.FK_ProjectTeam_User", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.Role in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="Role")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Role : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        public static Role CreateRole(int id, string name)
        {
            Role role = new Role();
            role.Id = id;
            role.Name = name;
            return role;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for TeamRoles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_Role", "ProjectTeam")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProjectTeam> TeamRoles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_Role", "ProjectTeam");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_Role", "ProjectTeam", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="email">Initial value of Email.</param>
        public static User CreateUser(int id, string name, string email)
        {
            User user = new User();
            user.Id = id;
            user.Name = name;
            user.Email = email;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Pwdhash in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Pwdhash
        {
            get
            {
                return this._Pwdhash;
            }
            set
            {
                this.OnPwdhashChanging(value);
                this.ReportPropertyChanging("Pwdhash");
                this._Pwdhash = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Pwdhash");
                this.OnPwdhashChanged();
            }
        }
        private string _Pwdhash;
        partial void OnPwdhashChanging(string value);
        partial void OnPwdhashChanged();
        /// <summary>
        /// There are no comments for OwnedIssues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_User", "Issue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Issue> OwnedIssues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Issue>("bugtrackerModel.FK_Issue_User", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Issue>("bugtrackerModel.FK_Issue_User", "Issue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for AssignedIssues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_User1", "Issue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Issue> AssignedIssues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Issue>("bugtrackerModel.FK_Issue_User1", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Issue>("bugtrackerModel.FK_Issue_User1", "Issue", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProjectTeams in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_ProjectTeam_User", "ProjectTeam")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ProjectTeam> ProjectTeams
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_User", "ProjectTeam");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ProjectTeam>("bugtrackerModel.FK_ProjectTeam_User", "ProjectTeam", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for bugtrackerModel.IssueType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Type
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="bugtrackerModel", Name="IssueType")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class IssueType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new IssueType object.
        /// </summary>
        /// <param name="type">Initial value of Type.</param>
        public static IssueType CreateIssueType(string type)
        {
            IssueType issueType = new IssueType();
            issueType.Type = type;
            return issueType;
        }
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Issues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("bugtrackerModel", "FK_Issue_IssueType", "Issue")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Issue> Issues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Issue>("bugtrackerModel.FK_Issue_IssueType", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Issue>("bugtrackerModel.FK_Issue_IssueType", "Issue", value);
                }
            }
        }
    }
}
